Traceback (most recent call last):
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# comparison between gradients acquired from manually implemented backpropagation
# and gradients acquired with the help of torch.autograd

import torch
import numpy as np


# numpy implementation
def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.tanh(x) ** 2

np.random.seed(42)
X = np.linspace(-2, 2, 100).reshape(-1, 1)
y = 3 * X**2 + 2 * X + 1 + np.random.normal(0, 0.5, size=(100, 1))

input_size = 1
hidden_size = 10
output_size = 1

W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))

W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))


Z1 = X @ W1 + b1
A1 = tanh(Z1)
Z2 = A1 @ W2 + b2
y_pred = Z2

loss = np.mean((y_pred - y) ** 2)

dL_dy =  2 * (y_pred - y) / len(y)
dL_dW2 = A1.T @ dL_dy
dL_db2 = np.sum(dL_dy, axis=0, keepdims=True)

dL_dA1 = dL_dy @ W2.T
dL_dW1 = X.T @ (dL_dA1 * tanh_derivative(Z1))
dL_db1 = np.sum(dL_dA1 * tanh_derivative(Z1), axis=0, keepdims=True)

# Gradients
print("Gradients (numpy):")
print(f"dL/dW1: {dL_dW1}")
print(f"dL/db1: {dL_db1}")
print(f"dL/dW2: {dL_dW2}")
print(f"dL/db2: {dL_db2}")

# pytorch implementation
X_torch = torch.from_numpy(X).float()
y_torch = torch.from_numpy(y).float()

W1_torch = torch.from_numpy(W1).float()
W1_torch.requires_grad = True

b1_torch = torch.from_numpy(b1).float()
b1_torch.requires_grad = True

W2_torch = torch.from_numpy(W2).float()
W2_torch.requires_grad = True

b2_torch = torch.from_numpy(b2).float()
b2_torch.requires_grad = True

z1 = torch.matmul(X_torch, W1_torch) + b1_torch  # Input to hidden layer
h = torch.tanh(z1)  # Activation function
z2 = torch.matmul(h, W2_torch) + b2_torch  # Hidden to output layer
y_pred_torch = z2  # Output (no activation)

# Loss
loss = torch.mean((y_pred_torch - y_torch) ** 2)  # MSE Loss

# Backward pass
loss.backward()

# Gradients
print("Gradients (autograd):")
print(f"dL/dW1: {W1_torch.grad}")
print(f"dL/db1: {b1_torch.grad}")
print(f"dL/dW2: {W2_torch.grad}")
print(f"dL/db2: {b2_torch.grad}")

# We can observe that the computed gradients are identical.
------------------

----- stderr -----

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 577, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/qh/w33tqq7j74181hmc1ky5lm080000gn/T/ipykernel_51383/376737619.py", line 4, in <module>
    import torch
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/ulye_kak_raz/Desktop/pinn-course/.venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
----- stdout -----
Gradients (numpy):
dL/dW1: [[ 0.93194246  0.09623944 -0.24700574 -4.22315891  0.96889322 -1.1249081
   0.00741088  5.82434013 -5.24203024 -3.97948723]]
dL/db1: [[ 2.75474399  0.18774652 -0.47538974 -9.1854101   1.82687535 -2.18765708
   0.02943826 10.99286246 -9.97334731 -7.4694597 ]]
dL/dW2: [[ 3.56240163]
 [ 1.98326435]
 [ 1.68198557]
 [ 2.97177957]
 [ 0.84730756]
 [-1.92219513]
 [-3.71640091]
 [-0.91390832]
 [-1.31165714]
 [ 0.39759271]]
dL/db2: [[-10.05776964]]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[13], line 53[0m
[1;32m     50[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mdL/db2: [39m[38;5;132;01m{[39;00mdL_db2[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m     52[0m [38;5;66;03m# pytorch implementation[39;00m
[0;32m---> 53[0m X_torch [38;5;241m=[39m [43mtorch[49m[38;5;241;43m.[39;49m[43mfrom_numpy[49m[43m([49m[43mX[49m[43m)[49m[38;5;241m.[39mfloat()
[1;32m     54[0m y_torch [38;5;241m=[39m torch[38;5;241m.[39mfrom_numpy(y)[38;5;241m.[39mfloat()
[1;32m     56[0m W1_torch [38;5;241m=[39m torch[38;5;241m.[39mfrom_numpy(W1)[38;5;241m.[39mfloat()

[0;31mRuntimeError[0m: Numpy is not available

